# Generated by Django 3.2.6 on 2021-09-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promise',
            name='deliver_by',
            field=models.DateField(blank=True, default=None),
        ),
    ]
