# Generated by Django 3.2.6 on 2021-09-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promises', '0002_promise_deliver_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promise',
            name='deliver_by',
            field=models.DateField(default=None, null=True),
        ),
    ]
