# Generated by Django 3.2.6 on 2021-11-05 22:16

import datetime
from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('promises', '0004_alter_promise_deliver_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promise',
            name='content',
            field=django_cryptography.fields.encrypt(models.TextField()),
        ),
        migrations.AlterField(
            model_name='promise',
            name='title',
            field=django_cryptography.fields.encrypt(
                models.CharField(max_length=200)),
        ),
    ]
