# Generated by Django 3.2.6 on 2021-11-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promises', '0005_auto_20211105_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promise',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='promise',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
