# Generated by Django 3.2.6 on 2021-10-26 20:12

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lie',
            name='title',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=500)),
        ),
    ]
