# Generated by Django 3.2.6 on 2021-10-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lies', '0002_alter_lie_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lie',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
