# Generated by Django 3.2.6 on 2021-10-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='reminder',
            field=models.CharField(choices=[('one month', 'ONE MONTH'), ('one week', 'ONE WEEK'), ('two days', 'TWO DAYS')], default='one week', max_length=50),
        ),
    ]
