# Generated by Django 3.2.6 on 2021-11-05 22:16

import datetime
from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0003_alter_date_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='reminder',
            field=django_cryptography.fields.encrypt(models.CharField(choices=[('one month', 'One Month Prior'), (
                'one week', 'One Week Prior'), ('two days', 'Two Days Prior')], default='one week', max_length=50)),
        ),
        migrations.AlterField(
            model_name='date',
            name='title',
            field=django_cryptography.fields.encrypt(
                models.CharField(max_length=200)),
        ),
    ]
