# Generated by Django 3.2.6 on 2021-11-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0005_alter_date_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
