# Generated by Django 3.2.6 on 2021-10-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='trait_type',
            field=models.CharField(choices=[('POSITIVE', 'Positive Trait'), ('NEGATIVE', 'Negative Trait')], default='POSITIVE', max_length=20),
        ),
    ]
