# Generated by Django 3.2.6 on 2021-11-05 22:16

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0002_alter_trait_trait_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='content',
            field=django_cryptography.fields.encrypt(models.TextField()),
        ),
        migrations.AlterField(
            model_name='trait',
            name='title',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=200)),
        ),
        migrations.AlterField(
            model_name='trait',
            name='trait_type',
            field=django_cryptography.fields.encrypt(models.CharField(choices=[('POSITIVE', 'Positive Trait'), ('NEGATIVE', 'Negative Trait')], default='POSITIVE', max_length=20)),
        ),
    ]
