# Generated by Django 3.2.6 on 2021-11-05 22:16

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0008_auto_20210914_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='content',
            field=django_cryptography.fields.encrypt(models.TextField()),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='title',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=200)),
        ),
    ]
