# Generated by Django 3.2.6 on 2021-11-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0009_auto_20211105_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
